# Generated by Django 2.2.6 on 2019-11-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=100)),
                ('merchant_email', models.EmailField(max_length=254, unique=True)),
                ('merchant_contact_no', models.IntegerField(unique=True)),
                ('merchant_password', models.CharField(max_length=20)),
            ],
        ),
    ]
